<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( function_exists( "register_field_group" ) ) {
	register_field_group( array(
		'id' => 'acf_acf-to-rest-api',
		'title' => 'ACF to REST API',
		'fields' => array(
			array(
				'key' => 'field_56929e796a97e',
				'label' => 'Basic',
				'name' => 'ag_',
				'type' => 'tab',
			),
			array(
				'key' => 'field_56929e6a6a97d',
				'label' => 'Text',
				'name' => 'ag_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_56929e886a97f',
				'label' => 'Text Area',
				'name' => 'ag_text_area',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array(
				'key' => 'field_56929e926a980',
				'label' => 'Number',
				'name' => 'ag_number',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_56929e9c6a981',
				'label' => 'Email',
				'name' => 'ag_email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_56929ea46a982',
				'label' => 'Password',
				'name' => 'ag_password',
				'type' => 'password',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_56929eb06a983',
				'label' => 'Content',
				'name' => 'ag_',
				'type' => 'tab',
			),
			array(
				'key' => 'field_56929eba6a984',
				'label' => 'Wysiwyg Editor',
				'name' => 'ag_wysiwyg_editor',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array(
				'key' => 'field_56929eca6a985',
				'label' => 'Image',
				'name' => 'ag_image',
				'type' => 'image',
				'save_format' => 'id',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array(
				'key' => 'field_56929edc6a986',
				'label' => 'File',
				'name' => 'ag_file',
				'type' => 'file',
				'save_format' => 'id',
				'library' => 'all',
			),
			array(
				'key' => 'field_56929eea6a987',
				'label' => 'Choice',
				'name' => 'ag_',
				'type' => 'tab',
			),
			array(
				'key' => 'field_56929ef36a988',
				'label' => 'Select',
				'name' => 'ag_select',
				'type' => 'select',
				'choices' => array(
					'red' => 'Red',
					'blue' => 'Blue',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array(
				'key' => 'field_56929f0c6a989',
				'label' => 'Checkbox',
				'name' => 'ag_checkbox',
				'type' => 'checkbox',
				'choices' => array(
					'red' => 'Red',
					'blue' => 'Blue',
				),
				'default_value' => '',
				'layout' => 'vertical',
			),
			array(
				'key' => 'field_56929f1c6a98a',
				'label' => 'Radio Button',
				'name' => 'ag_radio_button',
				'type' => 'radio',
				'choices' => array(
					'red' => 'Red',
					'blue' => 'Blue',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array(
				'key' => 'field_56929f3f6a98b',
				'label' => 'True False',
				'name' => 'ag_true_false',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array(
				'key' => 'field_56929f4b6a98c',
				'label' => 'Relational',
				'name' => 'ag_',
				'type' => 'tab',
			),
			array(
				'key' => 'field_56929f586a98d',
				'label' => 'Page Link',
				'name' => 'ag_page_link',
				'type' => 'page_link',
				'post_type' => array(
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array(
				'key' => 'field_56929f6c6a98e',
				'label' => 'Post Object',
				'name' => 'ag_post_object',
				'type' => 'post_object',
				'post_type' => array(
					0 => 'all',
				),
				'taxonomy' => array(
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array(
				'key' => 'field_56929f7a6a98f',
				'label' => 'Relationship',
				'name' => 'ag_relationship',
				'type' => 'relationship',
				'return_format' => 'id',
				'post_type' => array(
					0 => 'all',
				),
				'taxonomy' => array(
					0 => 'all',
				),
				'filters' => array(
					0 => 'search',
				),
				'result_elements' => array(
					0 => 'post_type',
					1 => 'post_title',
				),
				'max' => '',
			),
			array(
				'key' => 'field_56929fa66a990',
				'label' => 'Taxonomy',
				'name' => 'ag_taxonomy',
				'type' => 'taxonomy',
				'taxonomy' => 'category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array(
				'key' => 'field_56929fc26a991',
				'label' => 'User',
				'name' => 'ag_user',
				'type' => 'user',
				'role' => array(
					0 => 'all',
				),
				'field_type' => 'select',
				'allow_null' => 0,
			),
			array(
				'key' => 'field_56929fdc6a992',
				'label' => 'jQuery',
				'name' => 'ag_',
				'type' => 'tab',
			),
			array(
				'key' => 'field_569847521afca',
				'label' => 'Google Map',
				'name' => 'ag_google_map',
				'type' => 'google_map',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array(
				'key' => 'field_56929fef6a993',
				'label' => 'Date Picker',
				'name' => 'ag_date_picker',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'yy-mm-dd',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5692a0126a994',
				'label' => 'Color Picker',
				'name' => 'ag_color_picker',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array(
				'key' => 'field_5697b4924cbbb',
				'label' => 'Repeater',
				'name' => 'ag_repeater',
				'type' => 'repeater',
				'sub_fields' => array(
					array(
						'key' => 'field_5697b49f4cbbc',
						'label' => 'First name',
						'name' => 'ag_first_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5697b4b54cbbd',
						'label' => 'Last name',
						'name' => 'ag_last_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array(
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array(
			),
		),
		'menu_order' => 0,
	) );
}